on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: install yaml_support dependencies
        run: |
          pip install extensions/yaml_support
      - name: run yaml_support tests
        run: |
          python -m extensions.yaml_support.yaml_support.tests.test_lg_yaml_api
